ItemNames:
	db "PRANYBOLCI@"         ;db "MASTER BALL@"
	db "ULTRABOLCI@"      ;db "ULTRA BALL@"
	db "BANLYBOLCI@"         ;db "GREAT BALL@"
	db "BOLCYRPOKé@"        ;db "POKé BALL@"
	db "TCADYCARTU@"       ;db "TOWN MAP@"
	db "RELXISLU@"     ;db "BICYCLE@"
	db "?????@"
	db "@"    ;db "SAFARI BALL@" "travel-hunt ball"
	db "POKéCUK@"        ;db "POKéDEX@" "Pokemon-catalog"
	db "LUNRYROKCI@"    ;db "MOON STONE@"

	db "vidvelmikce@"    ;db "ANTIDOTE@"   "poison cure"
	db "fagvelmikce@"    ;db "BURN HEAL@"  "fire cure"
	db "bisyvelmikce@"   ;db "ICE HEAL@"   "ice cure"
	db "sipyvelmikce@"   ;db "AWAKENING@"  "sleep cure"
	db "fravelmikce@"    ;db "PARLYZ HEAL@""react cure"
	db "rolka'odja@"     ;db "FULL RESTORE@" "all-health-food"
	db "cluka'odja@"     ;db "MAX POTION@"   "full-heal-food"
	db "cibyka'odja@"    ;db "HYPER POTION@" "3-heal-food"
	db "relka'odja@"     ;db "SUPER POTION@" "2-heal-food"
	db "pavyka'odja@"    ;db "POTION@" "1-heal-food"

	db "ROKCYSINXA@"         ;db "BOULDERBADGE@"
	db "DJACYSINXA@"         ;db "CASCADEBADGE@"
	db "LINDYSINXA@"        ;db "THUNDERBADGE@"
	db "SKARYSINXA@"         ;db "RAINBOWBADGE@"
	db "PRUXYSINXA@"        ;db "SOULBADGE@"
	db "cimtu'asni@"     ;db "MARSHBADGE@"
	db "FAGMASINXA@"   ;db "VOLCANOBADGE@"
	db "DERTYSINXA@"         ;db "EARTHBADGE@"

	db "RIVLI'ASKO@"  ;db "ESCAPE ROPE@" "escape rope"
	db "pokma rivbi@"    ;db "REPEL@" "Pokemon avoid"
	db "laldyricyblu@"   ;db "OLD AMBER@" "aged tree blood"
	db "FAGRYROKCI@"    ;db "FIRE STONE@"
	db "LINDYROKCI@"    ;db "THUNDERSTONE@"
	db "DJACYROKCI@"    ;db "WATER STONE@"

	db "ka'ozengau@"     ;db "HP UP@"    "health increase make"
	db "LANBI@"          ;db "PROTEIN@"
	db "TIRSE@"          ;db "IRON@"
	db "sutyzengau@"     ;db "CARBOS@"   "speed increase make"
	db "bogjinme@"       ;db "CALCIUM@"
	db "rirci titspi@"   ;db "RARE CANDY@"
	db "boirokybi'o@"    ;db "DOME FOSSIL@"
	db "sarlyrokybi'o@"  ;db "HELIX FOSSIL@"
	db "mipri ckiku@"    ;db "SECRET KEY@"
	db "?????@"

	db "relxil pikta@"   ;db "BIKE VOUCHER"  should be xelxilma'e, too long.
	db "daxyla'eze'a@"   ;db "X ACCURACY@" "hit-probability-increase"
	db "pezli rokci@"    ;db "LEAF STONE@"
	db "CKIKYKARDA@"    ;db "CARD KEY@" "key card"
	db "solji spisa@"    ;db "NUGGET@" "gold piece"
	db "da'ivlize'a@"    ;db "PP UP@" "attack power increase"
	db "pokma kelci@"    ;db "POKé DOLL@"
	db "mulka'ogau@"     ;db "FULL HEAL@" "complete-healthy-make"
	db "cikygau@"        ;db "REVIVE@"
	db "ka'ocikygau@"    ;db "MAX REVIVE@"
	db "datni bandu@"    ;db "GUARD SPEC.@" "stat protect"
	db "poksairivy@"     ;db "SUPER REPEL@"
	db "pokcairivy@"     ;db "MAX REPEL@"
	db "vlida'igau@"     ;db "DIRE HIT@"
	db "SICNI@"          ;db "COIN@"
	db "DJACU@"    ;db "FRESH WATER@"
	db "SODVA@"          ;db "SODA POP@"
	db "nimryselpixy@"   ;db "LEMONADE@" "citrus-beverage"
	db "BLOTYPIKTA@"    ;db "S.S.TICKET@"
	db "SOLJYDENCI@"    ;db "GOLD TEETH@"

	db "XYZEIGUNTA@"       ;db "X ATTACK@"
	db "XYZEIBANDU@"       ;db "X DEFEND@"
	db "XYZEISUTRA@"       ;db "X SPEED@"
	db "XYZEI@"    ;db "X SPECIAL@"
	db "SICNYLANKA@"	 ;db "COIN CASE@"
	db "CINDU@"			 ;db "OAK's PARCEL@"
	db "DACTYFACKI@"    ;db "ITEMFINDER@" "object-seek-device"
	db "la.silf.lenjo@"  ;db "SILPH SCOPE@"
	db "FLANYRPOKé@"    ;db "POKé FLUTE@"
	db "lafmi'i ckiku@"  ;db "LIFT KEY@"
	db "crena'u fatri@"  ;db "EXP.ALL@"
	db "tolci'o grana@"  ;db "OLD ROD@"
	db "xamgu grana@"    ;db "GOOD ROD@"
	db "banli grana@"    ;db "SUPER ROD@"
	db "da'ivlize'a@"    ;db "PP UP@" "attack power increase" (duped?)
	db "pavyda'ika'o@"   ;db "ETHER@"
	db "relda'ika'o@"    ;db "MAX ETHER@"
	db "cirda'ika'o@"    ;db "ELIXER@"
	db "vonda'ika'o@"    ;db "MAX ELIXER@"

	; I think these are floors in a building?
	; Hard to translate them out of context.
	db "B2F@"
	db "B1F@"
	db "1F@"
	db "2F@"
	db "3F@"
	db "4F@"
	db "5F@"
	db "6F@"
	db "7F@"
	db "8F@"
	db "9F@"
	db "10F@"
	db "11F@"
	db "B4F@"
